# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

jdk:
  - oraclejdk11

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

install:
  - mvn install -P travis -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -P travis -B

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту gh0st84@mail.ru
notifications:
  email:
    recipients:
      - gh0st84@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="c5bb4d50-bb67-4c4c-9284-c5c69ba278a6"